"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 14:59:27.960765
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_counters'))
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trade', sa.String(length=80), nullable=False),
    sa.Column('active', sa.String(length=120), nullable=False),
    sa.Column('hrac', sa.String(length=8), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('crop', sa.String(length=40), nullable=False),
    sa.Column('formulation', sa.String(length=80), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('trade', name=op.f('uq_products_trade'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_hrac'), ['hrac'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_updated_at'), ['updated_at'], unique=False)

    op.create_table('species',
    sa.Column('latin', sa.String(length=80), nullable=False),
    sa.Column('local', sa.String(length=80), nullable=False),
    sa.Column('common', sa.String(length=80), nullable=False),
    sa.Column('cls', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('latin', name=op.f('pk_species'))
    )
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_updated_at'), ['updated_at'], unique=False)

    op.create_table('station_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=120), nullable=False),
    sa.Column('season_label', sa.String(length=40), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('threshold_published_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('threshold_published_by', sa.String(length=120), nullable=True),
    sa.Column('default_grid_m', sa.Integer(), nullable=False),
    sa.Column('default_units', sa.String(length=8), nullable=False),
    sa.Column('leaf_abstain_below', sa.Float(), nullable=False),
    sa.Column('model_aerial', sa.String(length=80), nullable=False),
    sa.Column('model_leaf', sa.String(length=80), nullable=False),
    sa.Column('leaf_model_size_mb', sa.Float(), nullable=True),
    sa.Column('app_latest_version', sa.String(length=40), nullable=True),
    sa.Column('app_min_version', sa.String(length=40), nullable=True),
    sa.Column('season_length_days', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_settings'))
    )
    with op.batch_alter_table('station_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('operator_code', sa.String(length=32), nullable=True),
    sa.Column('scope_all', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('last_active_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('operator_code', name=op.f('uq_users_operator_code'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('who', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('os', sa.String(length=60), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('storage_mb', sa.Integer(), nullable=True),
    sa.Column('pending_changes', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('install_id', name=op.f('uq_devices_install_id'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gate', sa.JSON(), nullable=False),
    sa.Column('landscape', sa.JSON(), nullable=False),
    sa.Column('capture_method', sa.String(length=16), nullable=False),
    sa.Column('captured_by_id', sa.String(length=32), nullable=True),
    sa.Column('captured_by_name', sa.String(length=120), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=False),
    sa.Column('perimeter_m', sa.Float(), nullable=False),
    sa.Column('archived_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_id'], ['users.id'], name=op.f('fk_fields_captured_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields')),
    sa.UniqueConstraint('client_id', name=op.f('uq_fields_client_id'))
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fields_updated_at'), ['updated_at'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('field_ids', sa.JSON(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_resets_token_hash'))
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('change_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('client_seq', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('op', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('owned_by_mobile', sa.Boolean(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_change_log_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_change_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log')),
    sa.UniqueConstraint('device_id', 'client_seq', name='uq_change_log_device_seq')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_seq'), ['seq'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('include', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('cells', sa.Integer(), nullable=False),
    sa.Column('zones', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_exports_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exports_field_id'), ['field_id'], unique=False)

    op.create_table('field_seasons',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('crop', sa.String(length=40), nullable=False),
    sa.Column('season', sa.String(length=40), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('row_spacing_cm', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=60), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_field_seasons_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_seasons')),
    sa.UniqueConstraint('field_id', 'season', name='uq_field_seasons_field_season')
    )
    with op.batch_alter_table('field_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_seasons_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_seasons_updated_at'), ['updated_at'], unique=False)

    op.create_table('leaf_scans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('captured_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('zone_label', sa.String(length=16), nullable=True),
    sa.Column('frame_id', sa.String(length=32), nullable=True),
    sa.Column('species_latin', sa.String(length=80), nullable=False),
    sa.Column('species_local', sa.String(length=80), nullable=True),
    sa.Column('weed_class', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('runner_up', sa.JSON(), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('leaf_seed', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('gnss_accuracy_m', sa.Float(), nullable=True),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('photo_content_type', sa.String(length=40), nullable=True),
    sa.Column('photo_bytes', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=80), nullable=True),
    sa.Column('annotation_note', sa.Text(), nullable=True),
    sa.Column('annotated_by', sa.String(length=32), nullable=True),
    sa.Column('annotated_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.String(length=80), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotated_by'], ['users.id'], name=op.f('fk_leaf_scans_annotated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_leaf_scans_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_leaf_scans_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_leaf_scans_operator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_leaf_scans_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaf_scans')),
    sa.UniqueConstraint('client_id', name=op.f('uq_leaf_scans_client_id'))
    )
    with op.batch_alter_table('leaf_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaf_scans_abstained'), ['abstained'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaf_scans_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaf_scans_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaf_scans_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaf_scans_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaf_scans_updated_at'), ['updated_at'], unique=False)

    op.create_table('quadrats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('frame_id', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('zone_label', sa.String(length=16), nullable=True),
    sa.Column('species_counts', sa.JSON(), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('recorded_by', sa.String(length=32), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_quadrats_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_quadrats_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quadrats')),
    sa.UniqueConstraint('client_id', name=op.f('uq_quadrats_client_id'))
    )
    with op.batch_alter_table('quadrats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quadrats_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quadrats_updated_at'), ['updated_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_refresh_tokens_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_fields',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_user_fields_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_fields_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'field_id', name=op.f('pk_user_fields'))
    )
    op.create_table('surveys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('field_season_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('flown_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('altitude_m', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=80), nullable=False),
    sa.Column('gsd_cm', sa.Float(), nullable=False),
    sa.Column('images', sa.Integer(), nullable=False),
    sa.Column('image_bytes', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('orthomosaic_key', sa.String(length=255), nullable=True),
    sa.Column('pipeline', sa.String(length=120), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('processed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_surveys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_season_id'], ['field_seasons.id'], name=op.f('fk_surveys_field_season_id_field_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_field_season_id'), ['field_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveys_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveys_updated_at'), ['updated_at'], unique=False)

    op.create_table('treatments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('field_season_id', sa.String(length=40), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('zone_labels', sa.JSON(), nullable=False),
    sa.Column('applied_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('product', sa.String(length=80), nullable=False),
    sa.Column('active_ingredient', sa.String(length=120), nullable=False),
    sa.Column('hrac_group', sa.String(length=8), nullable=False),
    sa.Column('dose_recorded', sa.String(length=32), nullable=False),
    sa.Column('dose_unit', sa.String(length=16), nullable=False),
    sa.Column('application_mode', sa.String(length=40), nullable=False),
    sa.Column('growth_stage', sa.String(length=40), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('operator_name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('water_litres', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('rotation_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_treatments_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_treatments_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_season_id'], ['field_seasons.id'], name=op.f('fk_treatments_field_season_id_field_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_treatments_operator_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatments')),
    sa.UniqueConstraint('client_id', name=op.f('uq_treatments_client_id'))
    )
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatments_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_field_season_id'), ['field_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_hrac_group'), ['hrac_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_updated_at'), ['updated_at'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('survey_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('locked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_processing_jobs_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_survey_id'), ['survey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_updated_at'), ['updated_at'], unique=False)

    op.create_table('survey_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_images_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_images'))
    )
    with op.batch_alter_table('survey_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_images_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_surfaces',
    sa.Column('survey_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_surfaces_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_id', name=op.f('pk_survey_surfaces'))
    )
    with op.batch_alter_table('survey_surfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_surfaces_updated_at'), ['updated_at'], unique=False)

    op.create_table('treatment_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('field_season_id', sa.String(length=40), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('survey_id', sa.String(length=32), nullable=True),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('dominant_class', sa.String(length=16), nullable=False),
    sa.Column('area_sqm', sa.Integer(), nullable=False),
    sa.Column('cell_count', sa.Integer(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('mean_infest_pct', sa.Float(), nullable=False),
    sa.Column('route_order', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_changed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('treated_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('treated_by', sa.String(length=32), nullable=True),
    sa.Column('efficacy_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_treatment_zones_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_season_id'], ['field_seasons.id'], name=op.f('fk_treatment_zones_field_season_id_field_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_treatment_zones_survey_id_surveys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treated_by'], ['users.id'], name=op.f('fk_treatment_zones_treated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_zones')),
    sa.UniqueConstraint('field_season_id', 'letter', name='uq_treatment_zones_season_letter')
    )
    with op.batch_alter_table('treatment_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_zones_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_zones_field_season_id'), ['field_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_zones_updated_at'), ['updated_at'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('field_season_id', sa.String(length=40), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('pre_survey_id', sa.String(length=32), nullable=True),
    sa.Column('follow_survey_id', sa.String(length=32), nullable=True),
    sa.Column('saved_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('saved_by', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('worst_efficacy_pct', sa.Integer(), nullable=True),
    sa.Column('field_delta_pct', sa.Integer(), nullable=True),
    sa.Column('chemical_saved_pct', sa.Float(), nullable=True),
    sa.Column('historical', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_verifications_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_verifications_field_id_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_season_id'], ['field_seasons.id'], name=op.f('fk_verifications_field_season_id_field_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follow_survey_id'], ['surveys.id'], name=op.f('fk_verifications_follow_survey_id_surveys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pre_survey_id'], ['surveys.id'], name=op.f('fk_verifications_pre_survey_id_surveys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], name=op.f('fk_verifications_saved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications')),
    sa.UniqueConstraint('client_id', name=op.f('uq_verifications_client_id'))
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_field_season_id'), ['field_season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_verifications_field_season_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_field_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('treatment_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_zones_updated_at'))
        batch_op.drop_index(batch_op.f('ix_treatment_zones_field_season_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_zones_field_id'))

    op.drop_table('treatment_zones')
    with op.batch_alter_table('survey_surfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_surfaces_updated_at'))

    op.drop_table('survey_surfaces')
    with op.batch_alter_table('survey_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_images_survey_id'))

    op.drop_table('survey_images')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_survey_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_treatments_hrac_group'))
        batch_op.drop_index(batch_op.f('ix_treatments_field_season_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_field_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_applied_at'))

    op.drop_table('treatments')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_updated_at'))
        batch_op.drop_index(batch_op.f('ix_surveys_status'))
        batch_op.drop_index(batch_op.f('ix_surveys_field_season_id'))

    op.drop_table('surveys')
    op.drop_table('user_fields')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('quadrats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quadrats_updated_at'))
        batch_op.drop_index(batch_op.f('ix_quadrats_field_id'))

    op.drop_table('quadrats')
    with op.batch_alter_table('leaf_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaf_scans_updated_at'))
        batch_op.drop_index(batch_op.f('ix_leaf_scans_resolved'))
        batch_op.drop_index(batch_op.f('ix_leaf_scans_field_id'))
        batch_op.drop_index(batch_op.f('ix_leaf_scans_device_id'))
        batch_op.drop_index(batch_op.f('ix_leaf_scans_captured_at'))
        batch_op.drop_index(batch_op.f('ix_leaf_scans_abstained'))

    op.drop_table('leaf_scans')
    with op.batch_alter_table('field_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_seasons_updated_at'))
        batch_op.drop_index(batch_op.f('ix_field_seasons_field_id'))

    op.drop_table('field_seasons')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_field_id'))
        batch_op.drop_index(batch_op.f('ix_exports_at'))

    op.drop_table('exports')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_log_seq'))
        batch_op.drop_index(batch_op.f('ix_change_log_entity'))
        batch_op.drop_index(batch_op.f('ix_change_log_device_id'))
        batch_op.drop_index(batch_op.f('ix_change_log_at'))

    op.drop_table('change_log')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_updated_at'))
        batch_op.drop_index(batch_op.f('ix_fields_archived_at'))

    op.drop_table('fields')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_updated_at'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('station_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_settings_updated_at'))

    op.drop_table('station_settings')
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_updated_at'))

    op.drop_table('species')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_updated_at'))
        batch_op.drop_index(batch_op.f('ix_products_hrac'))

    op.drop_table('products')
    op.drop_table('counters')
    # ### end Alembic commands ###
